version: '3.4'
services:
        master:
                build:
                        context: .
                        dockerfile: ./Dockerfile.alpine-latest
                image: pwn3server-alpinelatest
                container_name: master-alpinelatest.pwn3
                hostname: master.pwn3
                networks:
                        default:
                                aliases:
                                        - "master.pwn3"
                ports:
                        - "3333:3333"
                volumes:
                        - type: bind
                          source: "./server"
                          target: "/opt/pwn3/server"
                        - type: bind
                          source: "./client"
                          target: "/opt/pwn3/client"
                        - type: bind
                          source: "./postgres-data"
                          target: "/opt/pwn3/postgres-data"
                command: "/opt/pwn3/setup/masterserver-alpinelatest.sh"
        game:
                build:
                        context: .
                        dockerfile: ./Dockerfile.alpine-latest
                image: pwn3server-alpinelatest
                container_name: game-alpinelatest.pwn3
                hostname: game.pwn3
                networks:
                        default:
                                aliases:
                                        - "master.pwn3"
                ports:
                        - "3000-3010:3000-3010"
                volumes:
                        - type: bind
                          source: "./server"
                          target: "/opt/pwn3/server"
                        - type: bind
                          source: "./client"
                          target: "/opt/pwn3/client"
                command: "/opt/pwn3/setup/gameserver.sh"
                depends_on:
                        - master