# Use the latest alpine linux docker image as a base to start with a tiny image
FROM alpine:latest

ENV PWN3=/opt/pwn3

RUN apk add --no-cache \
  openrc \
  bash \
  libssl1.0 \
  nano \
  postgresql \
  && adduser pwn3 --system --shell /bin/bash --group

EXPOSE 5432

ADD --chown=pwn3 server/MasterServer/initdb.sql $PWN3/initdb.sql
ADD --chown=pwn3 setup $PWN3/setup

